baseurl = "https://thofstee.github.io"
languageCode = "en"
title = ""
theme = "hugo-theme-bleak"
# copyright = "&copy; <a href=\"https://github.com/thofstee\">Teguh Hofstee</a> 2016"
googleAnalytics = ""
description = "Your personal description"
keywords = ["keyword1", "keyword2"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/thofstee"
fa_icon = "fa-github"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

